image: docker

services:
  - docker:dind

variables:
  IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest

docker-build:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - docker build -t $IMAGE_LATEST .
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_LATEST

